<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.53">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matías Villaseca Torres">
<meta name="dcterms.date" content="2024-09-25">

<title>Proyecto Gestión Financiera</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="proyecto_gestion_financiera_files/libs/clipboard/clipboard.min.js"></script>
<script src="proyecto_gestion_financiera_files/libs/quarto-html/quarto.js"></script>
<script src="proyecto_gestion_financiera_files/libs/quarto-html/popper.min.js"></script>
<script src="proyecto_gestion_financiera_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="proyecto_gestion_financiera_files/libs/quarto-html/anchor.min.js"></script>
<link href="proyecto_gestion_financiera_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="proyecto_gestion_financiera_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="proyecto_gestion_financiera_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="proyecto_gestion_financiera_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="proyecto_gestion_financiera_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Proyecto Gestión Financiera</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Matías Villaseca Torres </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 25, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="descripción-activo-y-contexto" class="level1">
<h1>1.Descripción Activo y Contexto</h1>
<section id="definición" class="level2">
<h2 class="anchored" data-anchor-id="definición">Definición</h2>
<p>El sector tecnológico se caracteriza por la innovación continua en áreas como la inteligencia artificial y los semiconductores, que han transformado diversas industrias (Brynjolfsson &amp; McAfee, 2014).</p>
<p>El libro “The Second Machine Age: Work, Progress, and Prosperity in a Time of Brilliant Technologies” de Brynjolfsson y McAfee (2014) lo elegí en lugar de un artículo científico debido a su importancia para analizar el impacto que las tecnologías disruptivas como la inteligencia artificial y los avances en hardware han tenido en la economía y la sociedad.</p>
</section>
<section id="motivación" class="level2">
<h2 class="anchored" data-anchor-id="motivación">Motivación</h2>
<p>Elegí Nvidia como activo de estudio debido a su relevancia en la transformación digital global y su posicionamiento como uno de los actores clave en sectores emergentes como la inteligencia artificial, el gaming y el desarrollo de supercomputadoras. En los últimos años, Nvidia ha visto un crecimiento significativo en sus ingresos, impulsado por la creciente demanda de sus productos en sectores como los centros de datos y la inteligencia artificial. Además, la alta volatilidad de sus acciones proporciona un interesante caso de estudio para el análisis de opciones financieras.</p>
</section>
<section id="contexto" class="level2">
<h2 class="anchored" data-anchor-id="contexto">Contexto</h2>
<p>En los últimos cinco años, el precio de las acciones de Nvidia ha mostrado una volatilidad considerable, con un crecimiento significativo entre 2020 y 2022, impulsado por el auge de la inteligencia artificial y el gaming. Sin embargo, ha experimentado grandes fluctuaciones debido a la incertidumbre del mercado y a la especulación en torno a las tecnologías emergentes.</p>
</section>
</section>
<section id="análisis-de-variablesactivos" class="level1">
<h1>2.Análisis de Variables/Activos</h1>
<section id="precio-de-las-acciones-de-nvidia" class="level2">
<h2 class="anchored" data-anchor-id="precio-de-las-acciones-de-nvidia">2.1 Precio de las Acciones de Nvidia</h2>
<p>El análisis del precio de cierre de las acciones de Nvidia en los últimos cinco años, basándonos en los datos proporcionados, muestra: • Precio más reciente (al 6 de septiembre de 2024): 101.79 USD • Desviación Estándar Anualizada: 53.48% (volatilidad calculada a partir de los rendimientos diarios) Estos datos indican una alta volatilidad en el precio de las acciones, reflejando grandes fluctuaciones en el mercado. El gráfico a continuación muestra la evolución del precio de cierre de las acciones de Nvidia durante los últimos cinco años. Se puede observar una tendencia alcista significativa desde 2021, seguida de episodios de alta volatilidad, particularmente en 2023 y 2024. Este aumento en el precio refleja el crecimiento sostenido de Nvidia en el sector tecnológico, impulsado por el avance de la inteligencia artificial, los semiconductores y el gaming.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Suprimir los mensajes al cargar librerías</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(ggplot2))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(readr))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(dplyr))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Leer el archivo CSV sin mostrar el mensaje de especificación de columnas</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>nvidia_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"NVDA Historical Data (2).csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir 'Date' a formato de fecha solo una vez</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>nvidia_data<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(nvidia_data<span class="sc">$</span>Date, <span class="at">format =</span> <span class="st">"%m/%d/%Y"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir 'Vol.' de texto con "M" (millones) y "B" (billones) a numérico solo una vez</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>nvidia_data<span class="sc">$</span>Vol <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"M"</span>, <span class="st">"e6"</span>, <span class="fu">gsub</span>(<span class="st">"B"</span>, <span class="st">"e9"</span>, nvidia_data<span class="sc">$</span>Vol.)))</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el gráfico del precio</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nvidia_data, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Price)) <span class="sc">+</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Evolución del Precio de las Acciones de Nvidia"</span>,</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Fecha"</span>, <span class="at">y =</span> <span class="st">"Precio de Cierre (USD)"</span>) <span class="sc">+</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="proyecto_gestion_financiera_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="volumen-de-transacciones" class="level2">
<h2 class="anchored" data-anchor-id="volumen-de-transacciones">2.2 Volumen de Transacciones</h2>
<p>El volumen de transacciones se refiere al número de acciones de Nvidia compradas y vendidas en un período determinado. Un mayor volumen suele indicar un mayor interés en el activo y puede correlacionarse con la volatilidad y liquidez del mercado. El gráfico que se presenta a continuación ilustra la evolución del volumen de transacciones de las acciones de Nvidia durante los últimos cinco años. Se puede apreciar que los volúmenes de transacción han fluctuado de manera significativa, alcanzando picos en momentos de alta volatilidad y eventos clave de mercado. Esto sugiere que el interés de los inversores ha sido considerablemente alto en periodos de cambios importantes en el precio de la acción.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar las librerías necesarias y suprimir los mensajes al cargar</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(ggplot2))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(readr))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(dplyr))</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Leer el archivo CSV sin mostrar el mensaje de especificación de columnas</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>nvidia_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"NVDA Historical Data (2).csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir 'Date' a formato de fecha (solo una vez)</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>nvidia_data<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(nvidia_data<span class="sc">$</span>Date, <span class="at">format=</span><span class="st">"%m/%d/%Y"</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir 'Vol.' de texto con "M" (millones) y "B" (billones) a numérico (solo una vez)</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>nvidia_data<span class="sc">$</span>Vol <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"M"</span>, <span class="st">"e6"</span>, <span class="fu">gsub</span>(<span class="st">"B"</span>, <span class="st">"e9"</span>, nvidia_data<span class="sc">$</span>Vol.)))</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el gráfico del volumen de transacciones</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nvidia_data, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Vol)) <span class="sc">+</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Evolución del Volumen de Transacciones de Nvidia"</span>,</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Fecha"</span>, <span class="at">y =</span> <span class="st">"Volumen (número de acciones)"</span>) <span class="sc">+</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="proyecto_gestion_financiera_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="volatilidad" class="level2">
<h2 class="anchored" data-anchor-id="volatilidad">2.3 Volatilidad</h2>
<p>La volatilidad mide la variabilidad en el precio de las acciones. Una alta volatilidad sugiere que el precio de las acciones está sujeto a grandes fluctuaciones, lo que afecta la valoración de las opciones. En el siguiente gráfico, se representa la evolución de los rendimientos diarios de las acciones de Nvidia, que miden la volatilidad del activo. Se pueden notar picos de alta volatilidad, especialmente entre 2020 y 2023, que coinciden con eventos clave del mercado. Este comportamiento refleja la alta sensibilidad del precio de Nvidia a los cambios del mercado y la creciente especulación en torno a sus acciones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Suprimir los mensajes al cargar las librerías</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(ggplot2))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(readr))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(dplyr))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Leer el archivo CSV sin mostrar el mensaje de especificación de columnas</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>nvidia_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"NVDA Historical Data (2).csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir 'Date' a formato de fecha solo una vez</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>nvidia_data<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(nvidia_data<span class="sc">$</span>Date, <span class="at">format =</span> <span class="st">"%m/%d/%Y"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir 'Vol.' de texto con "M" (millones) y "B" (billones) a numérico solo una vez</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>nvidia_data<span class="sc">$</span>Vol <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"M"</span>, <span class="st">"e6"</span>, <span class="fu">gsub</span>(<span class="st">"B"</span>, <span class="st">"e9"</span>, nvidia_data<span class="sc">$</span>Vol.)))</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular los rendimientos diarios</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>nvidia_data <span class="ot">&lt;-</span> nvidia_data <span class="sc">%&gt;%</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Date) <span class="sc">%&gt;%</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Rendimientos =</span> (Price <span class="sc">-</span> <span class="fu">lag</span>(Price)) <span class="sc">/</span> <span class="fu">lag</span>(Price))</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el gráfico de rendimientos diarios</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nvidia_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Rendimientos)), <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Rendimientos)) <span class="sc">+</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"green"</span>) <span class="sc">+</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Evolución de los Rendimientos Diarios de Nvidia"</span>,</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Fecha"</span>, <span class="at">y =</span> <span class="st">"Rendimientos Diarios"</span>) <span class="sc">+</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="proyecto_gestion_financiera_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="activo-derivado-opciones-sobre-acciones-de-nvidia" class="level2">
<h2 class="anchored" data-anchor-id="activo-derivado-opciones-sobre-acciones-de-nvidia">3.Activo Derivado: Opciones sobre Acciones de Nvidia</h2>
</section>
</section>
<section id="descripción-del-activo-derivado" class="level1">
<h1>3.1 Descripción del Activo Derivado</h1>
<p>Las opciones sobre acciones son contratos financieros que permiten a los inversores comprar (call) o vender (put) acciones a un precio específico en una fecha futura. La valoración de estas opciones depende en gran medida del precio del activo subyacente, en este caso, las acciones de Nvidia.</p>
</section>
<section id="datos-de-evolución" class="level1">
<h1>3.2 Datos de Evolución</h1>
<p>Para valorar las opciones sobre acciones de Nvidia, consideramos los siguientes datos calculados a partir del archivo histórico: Precio más reciente de la acción (6 de septiembre de 2024): 101.79 USD Precio de Ejercicio: 35 USD Tiempo hasta el Vencimiento: 6 meses Volatilidad: 53.48% (volatilidad anualizada calculada a partir de los rendimientos diarios) Tasa de Interés Libre de Riesgo: 2% anual</p>
</section>
<section id="procedimiento-de-valoración" class="level1">
<h1>3.3 Procedimiento de Valoración</h1>
<p>Utilizaremos el modelo Black-Scholes para valorar una opción call. La fórmula es: C=S0⋅N(d1)-X⋅e-r⋅T⋅N(d2) donde: C = Precio de la opción call S0 = Precio actual de la acción (30.27 USD) X = Precio de ejercicio (35 USD) T = Tiempo hasta el vencimiento (0.5 años) R = Tasa de interés libre de riesgo (2% anual) σ (sigma) = Volatilidad (29.68 USD) N(d1) y N(d2) = Funciones de distribución acumulativa de la normal estándar Cálculos y Resultados: Calcular d1 y d2 usando las fórmulas: d1=(ln(S0/X)+(r+σ^2/2)⋅T )/(σ⋅√T) d2=d1-σ⋅√T Sustituir d1d_1d1 y d2d_2d2 en la fórmula de Black-Scholes para obtener el valor de la opción call.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Leer los datos del archivo CSV</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"NVDA Historical Data (2).csv"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir la columna 'Date' a formato Date</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(data<span class="sc">$</span>Date, <span class="at">format =</span> <span class="st">"%m/%d/%Y"</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenar los datos por fecha</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data[<span class="fu">order</span>(data<span class="sc">$</span>Date), ]</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir la columna 'Price' a numérica</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Price <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(data<span class="sc">$</span>Price)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular los rendimientos diarios</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Returns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">diff</span>(data<span class="sc">$</span>Price) <span class="sc">/</span> <span class="fu">head</span>(data<span class="sc">$</span>Price, <span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la volatilidad histórica (anualizada)</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>volatility <span class="ot">&lt;-</span> <span class="fu">sd</span>(<span class="fu">na.omit</span>(data<span class="sc">$</span>Returns)) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">252</span>)  <span class="co"># 252 días en un año</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Volatilidad histórica anualizada: %.2f%%</span><span class="sc">\n</span><span class="st">"</span>, volatility <span class="sc">*</span> <span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Volatilidad histórica anualizada: 53.48%</code></pre>
</div>
</div>
<section id="comparación-de-modelos" class="level2">
<h2 class="anchored" data-anchor-id="comparación-de-modelos">4. Comparación de Modelos</h2>
<p>En este análisis se emplearon tres modelos diferentes para valorar una opción call sobre las acciones de Nvidia: Black-Scholes, Árbol Binomial y Simulación Monte Carlo. A continuación, se presentan las conclusiones obtenidas de cada uno de estos modelos.</p>
</section>
</section>
<section id="modelo-black-scholes" class="level1">
<h1>4.1 Modelo Black-Scholes</h1>
<p>El modelo Black-Scholes es un enfoque teórico ampliamente utilizado para valorar opciones. Este modelo asume un mercado sin fricciones y volatilidad constante. Al aplicar este modelo a la opción call sobre las acciones de Nvidia, se obtuvo un valor de 67.15 USD.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Parámetros para el modelo Black-Scholes</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>S0 <span class="ot">&lt;-</span> <span class="fu">tail</span>(data<span class="sc">$</span>Price, <span class="dv">1</span>)  <span class="co"># Precio actual de la acción</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="dv">35</span>  <span class="co"># Precio de ejercicio</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="fl">0.5</span>  <span class="co"># Tiempo hasta el vencimiento (6 meses)</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fl">0.02</span>  <span class="co"># Tasa de interés libre de riesgo</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> volatility  <span class="co"># Volatilidad histórica</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular d1 y d2</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>d1 <span class="ot">&lt;-</span> (<span class="fu">log</span>(S0 <span class="sc">/</span> X) <span class="sc">+</span> (r <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> sigma<span class="sc">^</span><span class="dv">2</span>) <span class="sc">*</span> T) <span class="sc">/</span> (sigma <span class="sc">*</span> <span class="fu">sqrt</span>(T))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> d1 <span class="sc">-</span> sigma <span class="sc">*</span> <span class="fu">sqrt</span>(T)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Valor de la opción call (Modelo Black-Scholes)</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> S0 <span class="sc">*</span> <span class="fu">pnorm</span>(d1) <span class="sc">-</span> X <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>r <span class="sc">*</span> T) <span class="sc">*</span> <span class="fu">pnorm</span>(d2)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Valor de la opción call (Black-Scholes): %.2f USD</span><span class="sc">\n</span><span class="st">"</span>, C))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Valor de la opción call (Black-Scholes): 67.15 USD</code></pre>
</div>
</div>
<p>Este resultado se basa en los siguientes parámetros:</p>
<p>Precio actual de la acción: 101.79 USD Precio de ejercicio: 35 USD Tiempo hasta el vencimiento: 6 meses (0.5 años) Tasa de interés libre de riesgo: 2% Volatilidad histórica anualizada: 53.48%</p>
</section>
<section id="modelo-binomial" class="level1">
<h1>4.2 Modelo Binomial</h1>
<p>El modelo binomial permite valorar opciones dividiendo el tiempo hasta el vencimiento en varios pasos discretos, en los que la acción puede moverse hacia arriba o hacia abajo en cada paso. Esto ofrece mayor flexibilidad en comparación con el modelo Black-Scholes, ya que puede adaptarse a cambios en la volatilidad y en la estructura del mercado.</p>
<p>En este análisis, se utilizó un modelo binomial con 100 pasos. El valor de la opción call obtenido fue de 67.15 USD, lo que confirma la consistencia con el modelo Black-Scholes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Parámetros del modelo binomial</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100</span>  <span class="co"># Número de pasos</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>dt <span class="ot">&lt;-</span> T <span class="sc">/</span> N  <span class="co"># Incremento de tiempo por paso</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">exp</span>(sigma <span class="sc">*</span> <span class="fu">sqrt</span>(dt))  <span class="co"># Factor de subida</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> u  <span class="co"># Factor de bajada</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> (<span class="fu">exp</span>(r <span class="sc">*</span> dt) <span class="sc">-</span> d) <span class="sc">/</span> (u <span class="sc">-</span> d)  <span class="co"># Probabilidad ajustada al riesgo</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Inicializar matrices para el árbol binomial</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>price_tree <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, N <span class="sc">+</span> <span class="dv">1</span>, N <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>price_tree[<span class="dv">1</span>, <span class="dv">1</span>] <span class="ot">&lt;-</span> S0</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Construir el árbol de precios</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>(N <span class="sc">+</span> <span class="dv">1</span>)) {</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>i) {</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    price_tree[j, i] <span class="ot">&lt;-</span> S0 <span class="sc">*</span> u<span class="sc">^</span>(i <span class="sc">-</span> j) <span class="sc">*</span> d<span class="sc">^</span>(j <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el árbol de valores de la opción call</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>option_tree <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, N <span class="sc">+</span> <span class="dv">1</span>, N <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>option_tree[, N <span class="sc">+</span> <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">pmax</span>(<span class="dv">0</span>, price_tree[, N <span class="sc">+</span> <span class="dv">1</span>] <span class="sc">-</span> X)</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Retroceder para calcular el valor de la opción en el nodo inicial</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> N<span class="sc">:</span><span class="dv">1</span>) {</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>i) {</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    option_tree[j, i] <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="sc">-</span>r <span class="sc">*</span> dt) <span class="sc">*</span> (p <span class="sc">*</span> option_tree[j, i <span class="sc">+</span> <span class="dv">1</span>] <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> p) <span class="sc">*</span> option_tree[j <span class="sc">+</span> <span class="dv">1</span>, i <span class="sc">+</span> <span class="dv">1</span>])</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Valor de la opción call (Modelo Binomial)</span></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>valor_opcion_binomial <span class="ot">&lt;-</span> option_tree[<span class="dv">1</span>, <span class="dv">1</span>]</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Valor de la opción call (Árbol Binomial): %.2f USD</span><span class="sc">\n</span><span class="st">"</span>, valor_opcion_binomial))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Valor de la opción call (Árbol Binomial): 67.15 USD</code></pre>
</div>
</div>
<p>Este modelo tiene la ventaja de ser más flexible, pero en este caso específico, dado que las condiciones asumidas en el mercado son similares a las del modelo Black-Scholes (volatilidad constante y sin fricciones), ambos modelos producen el mismo resultado.</p>
</section>
<section id="simulación-monte-carlo" class="level1">
<h1>4.3 Simulación Monte Carlo</h1>
<p>La simulación Monte Carlo es un método numérico que genera múltiples trayectorias simuladas para los precios futuros de las acciones y, a partir de ellas, calcula el valor de la opción. En este análisis, se realizaron 10,000 simulaciones de posibles trayectorias de precios de Nvidia, basadas en la misma volatilidad y parámetros utilizados en los modelos anteriores.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulación de precios futuros utilizando Monte Carlo</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>num_simulaciones <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>num_dias <span class="ot">&lt;-</span> T <span class="sc">*</span> <span class="dv">252</span>  <span class="co"># Número de días en el horizonte temporal</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Inicializar matriz para precios simulados</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>precios_simulados <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, num_simulaciones, num_dias)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>precios_simulados[, <span class="dv">1</span>] <span class="ot">&lt;-</span> S0</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Simular precios futuros basados en volatilidad y tasa de interés</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>num_dias) {</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  rendimientos <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(num_simulaciones, <span class="at">mean =</span> r <span class="sc">/</span> <span class="dv">252</span>, <span class="at">sd =</span> sigma <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">252</span>))</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  precios_simulados[, i] <span class="ot">&lt;-</span> precios_simulados[, i <span class="sc">-</span> <span class="dv">1</span>] <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> rendimientos)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el valor de la opción call con Monte Carlo</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>payoffs_call <span class="ot">&lt;-</span> <span class="fu">pmax</span>(<span class="dv">0</span>, precios_simulados[, num_dias] <span class="sc">-</span> X)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>valor_opcion_mc <span class="ot">&lt;-</span> <span class="fu">mean</span>(payoffs_call) <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>r <span class="sc">*</span> T)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"El valor estimado de la opción call (Monte Carlo)fue: %.2f USD</span><span class="sc">\n</span><span class="st">"</span>, valor_opcion_mc))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El valor estimado de la opción call (Monte Carlo)fue: 67.37 USD</code></pre>
</div>
</div>
<p>ligeramente superior a los valores obtenidos con los modelos de Black-Scholes y Binomial. Esta diferencia puede deberse a la naturaleza probabilística del método Monte Carlo, que permite modelar con mayor flexibilidad las fluctuaciones del mercado.</p>
<p>Además, se utilizó la simulación Monte Carlo para valorar una opción put. El valor estimado para la opción put fue de 0.02 USD, lo que sugiere que la probabilidad de que el precio de la acción de Nvidia caiga por debajo del precio de ejercicio de 35 USD en los próximos seis meses es muy baja.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulación para calcular el valor de la opción put</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>payoffs_put <span class="ot">&lt;-</span> <span class="fu">pmax</span>(<span class="dv">0</span>, X <span class="sc">-</span> precios_simulados[, num_dias])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>valor_put_mc <span class="ot">&lt;-</span> <span class="fu">mean</span>(payoffs_put) <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>r <span class="sc">*</span> T)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Valor estimado de la opción put (Monte Carlo): %.2f USD</span><span class="sc">\n</span><span class="st">"</span>, valor_put_mc))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Valor estimado de la opción put (Monte Carlo): 0.02 USD</code></pre>
</div>
</div>
</section>
<section id="comparación-y-conclusiones" class="level1">
<h1>4.4 Comparación y Conclusiones</h1>
<p>Los resultados obtenidos a través de los tres modelos son bastante consistentes, especialmente entre los modelos Black-Scholes y Binomial, que arrojaron el mismo valor para la opción call (67.15 USD). Esto es esperable dado que ambos modelos utilizan suposiciones similares sobre la estructura de volatilidad y el mercado sin fricciones.</p>
<p>Por otro lado, el modelo Monte Carlo mostró un valor ligeramente superior para la opción call</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"El valor estimado de la opción call (Monte Carlo)fue: %.2f USD</span><span class="sc">\n</span><span class="st">"</span>, valor_opcion_mc))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El valor estimado de la opción call (Monte Carlo)fue: 67.37 USD</code></pre>
</div>
</div>
<p>lo que puede explicarse por la naturaleza probabilística de las simulaciones y su capacidad para modelar una mayor variedad de trayectorias de precios.</p>
<p>Además, la simulación de Monte Carlo permitió valorar una opción put, que arrojó un valor de 0.02 USD, demostrando que, bajo las condiciones actuales, es poco probable que el precio de la acción de Nvidia caiga por debajo del precio de ejercicio en el corto plazo.</p>
<p>En conclusión, aunque los tres métodos ofrecen resultados consistentes, el modelo binomial y el modelo Monte Carlo ofrecen mayor flexibilidad para escenarios en los que la volatilidad o las condiciones del mercado no son constantes. Sin embargo, en este caso particular, el modelo Black-Scholes sigue siendo una herramienta eficaz para valorar las opciones, dada la similitud de los resultados obtenidos.</p>
<section id="bibliografía" class="level2">
<h2 class="anchored" data-anchor-id="bibliografía">5.Bibliografía</h2>
<p>Brynjolfsson, E., &amp; McAfee, A. (2014). The Second Machine Age: Work, Progress, and Prosperity in a Time of Brilliant Technologies. W. W. Norton &amp; Company. Muro, M., &amp; Liu, S. (2020). AI and the Economy: How Artificial Intelligence is Transforming the Workforce. Brookings Institution. Venkatesh, V., Morris, M. G., Davis, G. B., &amp; Davis, F. D. (2003). User Acceptance of Information Technology: Toward a Unified View. MIS Quarterly, 27(3), 425-478. Jouppi, N. P., Young, C., Patil, N., &amp; Patterson, D. (2017). In-Datacenter Performance Analysis of a Tensor Processing Unit. Proceedings of the 44th Annual International Symposium on Computer Architecture (ISCA), 1-12.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>